check if branch already exists

diff --git a/.github/workflows/new_rdp.yml b/.github/workflows/new_rdp.yml
--- a/.github/workflows/new_rdp.yml
+++ b/.github/workflows/new_rdp.yml
@@ -44,6 +44,16 @@ jobs:
           # run script
           bash ./tools/new_rdp.sh ${{ github.event.inputs.date }}
 
+      - name: Check if git branch aready exists
+        shell: bash
+        run: |
+          if test (git ls-remote | grep rdp/${{ github.event.inputs.date }})
+            echo "::error::La branche existe déjà. Le risque d'écrasement est trop important !"
+            exit 1
+          else
+            echo "::notice::La branche de la prochaine RDP n'existe pas encore et sera créée."
+          end
+
       - name: New branch
         run: |
           git config user.name ${{ github.actor }}
