Try again

diff --git a/.github/workflows/new_rdp.yml b/.github/workflows/new_rdp.yml
--- a/.github/workflows/new_rdp.yml
+++ b/.github/workflows/new_rdp.yml
@@ -41,9 +41,14 @@ jobs:
       - name: Check if git branch aready exists
         shell: bash
         run: |
-          if test (git ls-remote | grep rdp/${{ github.event.inputs.date }})
-            echo "::error::La branche existe déjà. Le risque d'écrasement est trop important !"
-            exit 1
+          local existed_in_remote=$(git ls-remote --heads origin rdp/${{ github.event.inputs.date }})
+
+          if [[ -z ${existed_in_remote} ]]; then
+              echo "::notice::La branche de la prochaine RDP n'existe pas encore et sera créée."
+              echo 0
+          else
+              echo "::error::La branche existe déjà. Le risque d'écrasement est trop important !"
+              exit 1
           else
             echo "::notice::La branche de la prochaine RDP n'existe pas encore et sera créée."
           end
